### PR TITLE
[Maintenance] Changes following camila_sao_paulo update 

### PR DESCRIPTION
**Pull request by Mxrcon**
@abhi18av Following your updates on camila_sao_paulo i took some time to update this pipeline following the modifications on the commit id =`d62efe0f03faec81d7ece07973b608af988cfadd`, you can check the updates here

## Pull request content:

1. Makefile instead of Taskfile
2. updates to create_mock_data.sh
3. update to gitignore

## Ending

Feel free to make any questions you have, to discuss or criticize something. I'm here to hear you and at your disposal,

Hope we have a merge!, 
Davi

### CODE REVIEW

**Review by abhi18av — CHANGES_REQUESTED** [review]
@Mxrcon , this PR requires some Git magic (cleanup) on your side. 

There are 66 commits and 22 changed file 🤯

**Comment by Mxrcon** [comment]
> @Mxrcon , this PR requires some Git magic (cleanup) on your side.
> 
> There are 66 commits and 22 changed file exploding_head

@abhi18av true, i'll do this cleanup sorry for the inconvenience

**Comment by Mxrcon** [comment]
@abhi18av I cleaned my branch, but for some reason it maintained the high commit number

**Review by abhi18av — CHANGES_REQUESTED** [review]
@Mxrcon , this is a learning experience. I request you to try harder 😉 

This should be only a single commit.

**Comment by Mxrcon** [comment]
@abhi18av ok! I'll check what is happening here

**Comment by Mxrcon** [comment]
@abhi18av my lazy but working solution: creating a new branch starting from the right base and then cherry picking the commits and them pushing with --force

**Comment by abhi18av** [comment]
> @abhi18av my lazy but working solution: creating a new branch starting from the right base and then cherry picking the commits and them pushing with --force


Good, remember this solution. This will help alot in future 😉

**Comment by Mxrcon** [comment]
@abhi18av Ok! Thank you!

**Pull request merged**
