### PR TITLE
[Suggestion] Updating Read-me

### PR DESCRIPTION
**Pull request by Mxrcon**
# Updating Read-me
## Pull request greeting:
Hello there, @abhi18av. I took some time to update the `READ-ME.md` of this project, as this will make the project more easy to understand for new users, and will provide a first-local-use guide that will be very useful to inexperienced users and also to experienced. I also generated a dag file and converted it to png to show how this pipeline works.
 
## Pull request content:
* new `READ-ME.md`
* png containin dag.png
## PR ending:
If you have and question, doubt or critic fell free to contact me. I'm on your disposal to make any changes you want to.

Hope we have a merge.

### CODE REVIEW

**Comment by abhi18av** [comment]
@Mxrcon , on this PR you might need to resolve the conflicts before I can merge.

**Comment by Mxrcon** [comment]
@abhi18av I tried to resolve the conflicts here, hope it worked :+1:

**Review by abhi18av — APPROVED** [review]
Thanks for your contribution @Mxrcon !

**Comment by Mxrcon** [comment]
@abhi18av :) Thank you too!

**Pull request merged**
